- WheelWizard/Utils/DirectoryHandler.cs
- WheelWizard/Utils/RetroRewindLauncher.cs
- WheelWizard/Views/Pages/ModsPage.xaml.cs
When searching for files to load as mods only SZS and BRSTM archives were considered. This pull request introduces the missing ARC, BRSAR, and THP file filters into the related functions. 
This pull request also includes the starting argument of `--config=Dolphin.Core.EnableCheats=False` when starting Dolphin for use with Retro Rewind. I included this to prevent crashes from conflicting codes. It also doesn't require users to disable cheats in Dolphin every time they wish to launch Retro Rewind.
> Fix missing file types when searching for Mod Files. Disable cheats in Dolphin starting arguments when launching Retro Rewind.

- README.md
- WheelWizard/Services/Settings/LinuxDolphinInstaller.cs
- **Purpose of this PR:** Fix the issue where the system-wide Dolphin Flatpak installation fails without specifying why exactly (not the expected administrator pop-up)
- **How to Test:** On a default Arch Linux machine with the default `arch` user configuration (pre-built images), this behavior can be reproduced because with `flatpak` installed, the `arch` user does not have the privileges to perform a system-wide install without a prompt for the `root` password. The installation will fail without the usual "unauthorized" error, but a generic one, due to not using `pkexec`. If the `arch` user is added to the `wheel` group, however, the installation succeeds.
- **What Has Been Changed:** The invocation of the `flatpak install` command: it was changed to use `pkexec`, as well as the …
> fix: Authentication for system Flatpak installation (`polkit`)

- WheelWizard/Services/Installation/AutoUpdater/AutoUpdaterLinux.cs
- WheelWizard/Services/Installation/RetroRewindInstaller.cs
- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
- WheelWizard/Services/Launcher/Helpers/MiiChannelLaunchHelper.cs
- WheelWizard/Services/Launcher/RrLauncher.cs
- WheelWizard/Services/PathManager.cs
- WheelWizard/Services/Settings/LinuxDolphinInstaller.cs
- WheelWizard/Services/Settings/SettingsManager.cs
- WheelWizard/Services/Storage/FilePickerHelper.cs
- WheelWizard/Services/UrlProtocol/UrlProtocolManager.cs
- WheelWizard/Services/WiiManagement/SaveData/GameDataLoader.cs
- WheelWizard/Views/Pages/Settings/WhWzSettings.axaml.cs
- build-mac.sh
- **Purpose of this PR:** Fix the path handling on Linux to use the folders in the same way Dolphin users would expect them to be handled. Flatpak builds should now also work as expected. The broader goal is also to fix the handling of spaces in paths on all platforms (especially on macOS, to drop the `~/.config` directory in favor of `~/Library/Application Support`).
- **How to Test:** For Linux, I tested it on a default Arch Linux image with Plasma installed as a DE using the PKGBUILD of the AUR with a local source `.tar.gz`. Further, I had the Dolphin *natively* installed **and** as a Flatpak to test how it behaves. To test the handling of spaces, a test user can be created to test the Dolphin user folder path. The Dolphin executable path can also be tested with a symlink containing a …
> fix: Use sane path handling

- WheelWizard/Helpers/EnvHelper.cs
- WheelWizard/Services/Settings/LinuxDolphinInstaller.cs
- **Purpose of this PR:** Fix the way Linux package managers are called to install the `flatpak` package.
- **How to Test:** On any Arch Linux image, the fact that `pacman -S install -y flatpak` will lead to some error message can be reproduced.
- **What Has Been Changed:** The method in `EnvHelper` now returns the right  command with all required flags, handling `pacman` differently. The returned value is just concatenated with `" flatpak"` and that is used to install the package now.
- **Related Issue:** #59
> fix: Use correct options and subcommands for all package managers

- WheelWizard/Services/Installation/RetroRewindUpdater.cs
The zip extraction of the Retro Rewind updater had a directory traversal attack vector which has now been fixed.
> Directory traversal attack prevention in zip extraction

- Flatpak/io.github.TeamWheelWizard.WheelWizard.desktop
This is a small fix that should fix the window managers' associations to the WheelWizard windows (e.g. in the task bar).
> fix: Specify `StartupWMClass` for correct window association

- WheelWizard/Helpers/EnvHelper.cs
- WheelWizard/Program.cs
- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
- WheelWizard/Services/PathManager.cs
- WheelWizard/Services/Settings/LinuxDolphinInstaller.cs
- WheelWizard/Services/Settings/SettingsManager.cs
This PR is a small improvement to the way relative paths are already handled.
For Flatpak-sandboxed WheelWizard, this will use `$HOME` as the default base directory for resolving relative paths, while other configurations still default to the directory of the WheelWizard executable. Additionally, this can now be overridden with `WW_BASEDIR`.
> feat: Improve relative paths and enable overriding the base dir

- .editorconfig
Code conventions and formatting where a little bit all over the place. So I used `dotnet new editorconfig` which is the default config for dotnet and removed some of the duplicate properties.
(not applicable)
- .editorconfig
(not applicable)
> New .editorconfig

- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
This only reorders the permissions given to the Dolphin Flatpak such that read-only permissions do not affect the required read-write permissions of e.g. the user folder in some weird edge cases.
> fix: Add read-write permissions only after all read-only permissions

- WheelWizard/Helpers/HttpClientHelper.cs
fix to make sure it does not infinitly load in the start screen if you dont have internet or smth
start the app and make sure everything keeps working
added a timeout
https://discord.com/channels/1253384439937896560/1356337934063632595
> fix: Prevent infinite loading on start page

- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
Expose this environment variable to non-Flatpak Dolphin executables on Linux to fix crashes on Wayland.
A machine with a recent KDE Plasma version on Wayland can be used along with a native `dolphin-emu` installation to test that e.g. the Software Renderer backend works to launch Retro Rewind. `/proc/<pid>/environ` with `pid` of the `dolphin-emu` process should show the `QT_QPA_PLATFORM=xcb` environment variable. I've tested this and it works.
The Dolphin launcher will now add this environment variable where needed on Linux systems to the launched process.
#95
> fix: Add `QT_QPA_PLATFORM` environment variable

- WheelWizard/Program.cs
- WheelWizard/Services/Settings/SettingsManager.cs
- WheelWizard/Services/Settings/WhWzSettingManager.cs
Fix the bug where a corrupt `config.json` file (filled with `\0` bytes, for example) would crash WheelWizard.
Write a single `\0` byte at the start of the JSON file and remove all other contents. Then open WheelWizard – it should not crash anymore but log the exception and the loaded config is empty. Entering the settings again and hitting save should overwrite the file in a way that the `\0` byte is gone.
The initial setup of the application was rewritten to pass the service provider to the `LoadSettings` method (for logging purposes).
#100
> fix: Handle the case of a corrupt JSON config

- WheelWizard.Test/GlobalUsings.cs
- WheelWizard.Test/Shared/OperationResult/OperationResultTests.cs
- WheelWizard.Test/Shared/Services/AvaloniaLoggerAdapterTests.cs
- WheelWizard/Features/AutoUpdating/Platforms/LinuxUpdatePlatform.cs
- WheelWizard/Features/AutoUpdating/Platforms/WindowsUpdatePlatform.cs
- WheelWizard/Shared/OperationResult/OperationError.cs
- WheelWizard/Shared/OperationResult/OperationResult.cs
- WheelWizard/Shared/OperationResult/OperationResult`1.cs
- WheelWizard/Shared/Services/ApiCaller.cs
Sometimes we need to convert exceptions to operation results.
(not applicable)
- Added extra exception handling methods to the operation result implementation.
- Made OperationResult<T> have a nullability constraint due to the MemberNotNull attributes
> Operationresult exception handling

- WheelWizard/Features/WiiManagement/GameDataLoaderService.cs
Fix an issue where licenses with guest Miis were not showing up properly due to failed Mii parsing.
Load a save file that contains a license with a guest Mii (e.g., a Mii created without a Mii Channel ID).
Confirm that the license now appears in the UI and no exception or error occurs during parsing.
Modified the ParseUser method to fall back to a dummy MiiData with placeholder name ("no name") when Mii parsing fails.
Ensures the license is still loaded even if the associated Mii is invalid or missing.
[Issue #113](https://github.com/TeamWheelWizard/WheelWizard/issues/113)
[not needed] You have created relevant tests
> Fix licences without valid mii not showing

- WheelWizard/Features/WiiManagement/GameDataLoaderService.cs
- WheelWizard/Views/Pages/UserProfilePage.axaml.cs
This PR addresses two open issues: the cancel action of Mii renaming (should not do anything) and the order of licenses in the WheelWizard GUI.
Open the rename dialog for a mii and cancel – it should now cancel the operation without an additional popup. For the license order, test with an erased license in a spot that's above other existing licenses. The order should be as expected now based on the order in Mario Kart Wii itself. I've tested these cases for myself, and I can confirm they work as expected now.
For the renaming, an additional check has been added for no-op renames (same name, `null` if canceled). The parsing of users has been changed such that the order of licenses is the same as in the game itself (adding dummy users directly inside the loop).
#114
> fix: Improve Mii name and license behavior

- WheelWizard/Views/Layout.axaml.cs
- WheelWizard/Views/Pages/UserProfilePage.axaml.cs
Fix a bug,. when you switch your primary license your friendcount would not instantly update
also fixed an edge case when switching regions your selected license would be a no license
Have 2 licenses, 1 containing x amount of friends and another containing different amount of friends, switch between them as the primary user. You should see your friendcount in the sidebar update. Same goes for switching regions
UpdateFriends has been made its own function to be called. 
https://github.com/TeamWheelWizard/WheelWizard/issues/115
- [not needed] You have created relevant tests
> My profile fixes

- Flatpak/io.github.TeamWheelWizard.WheelWizard.metainfo.xml
This is just to keep track of the missing release entry for the next release.
As described in the comment, future releases should be added here as well with their date in addition to bumping the version number of the project (assuming this makes it to `flathub` soon, of course).
Once the next release is known, we can enter these two values (release version + date).
> fix: Update `.metainfo.xml` with next release

- WheelWizard/Services/PathManager.cs
This is just to check if it's actually the same directory on Linux based on the absolute path, not if it's exactly the same absolute path string.
> fix: Use absolute user-specified paths in the checks

- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
This is a small fix for Flatpak users. If the save folder did not exist yet, the game would not have the permission to the save folder, causing the game to not even load for new users.
> fix: Create save folder if it does not exist yet when granting Dolphin Flatpak permissions

- WheelWizard/Views/Pages/Settings/WhWzSettings.axaml.cs
This small change is just so we don't need to care about using `pkexec` or performing system or user-wide installations for the users if they're using the Flatpak version already and should be able to install it themselves. The installation popup won't be shown anymore if Wheel Wizard itself is a Flatpak.
> fix: Disable Dolphin Flatpak installation popup in the Flatpak version

- WheelWizard/Services/ModManager.cs
- WheelWizard/Views/BehaviorComponent/FeedbackTextBox.axaml.cs
- WheelWizard/WheelWizard.csproj
Fix a path escape bug when naming mods
call a mod "." it should not let you
extra validation
> Fix path escape

- Flatpak/io.github.TeamWheelWizard.WheelWizard.metainfo.xml
- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
- WheelWizard/WheelWizard.csproj
Enable Flatpak portal paths as user folders without permission issues. Furthermore, we bump the version number(s) to be able to release this to `flathub` (not just in the `.csproj`).
This was tested by using the file picker for the user folder, creating a `/run/user/...` path. Dolphin is granted the necessary permissions and Wheel Wizard is also able to work with that folder.
The Flatpak Dolphin permission fixing logic. We try to fix portal paths where applicable, not just for the game file. This should still work if we made `RiivolutionWhWzFolderPath` configurable in the GUI in the future.
#88
> fix: Improve Flatpak permission handling and use of portals

- WheelWizard/Views/Layout.axaml
- WheelWizard/Views/Layout.axaml.cs
when the OS is mac, the custom minimuse and close button are disabled, and we make sure we use the mac close and minimise button
run this on your own OS. and make sure it still looks nice. If you want oyu can also run it on other operating systems
- disable and enable the topbar buttons based on the OS. 
- Move the WhWz logo a little dow if its MacOS
not related
> feat: mac topbar

- WheelWizard.Test/Features/MiiDbServiceTest.cs
- WheelWizard/Features/WiiManagement/GameDataLoaderService.cs
- WheelWizard/Features/WiiManagement/MiiRepositoryService.cs
- WheelWizard/Features/WiiManagement/MiiSerializer.cs
- WheelWizard/Services/ModManager.cs
- WheelWizard/Views/BehaviorComponent/FeedbackTextBox.axaml.cs
Run tests, they should all pass.
Since the beginning of wheel wizard, ID's have been read like little endian,
Mii ID's are stored in Big endian, but code was reading it as little endian, this was not "bad".
But if we want correctness this is the correct way of parsing it
> Endianness fixes

- WheelWizard/Services/Installation/RetroRewindUpdater.cs
Currently, the Retro Rewind update process gets terminated with relative user folders due to the way the `ApplyFileDeletionsBetweenVersions` method is written. Absolute paths are compared to potentially relative `PathManager.RiivolutionWhWzFolderPath` paths. The obvious fix would be to also use an absolute `PathManager.RiivolutionWhWzFolderPath` in this method.
Use a relative user folder. Without this patch it should fail with the "Invalid file path detected" message due to the fact that the `StartsWith` calls can never be `true`. With this patch, applying the file deletions should work even with relative user folder configurations.
Fix the checks aborting the update if directory traversal is detected.
#140
> fix: Patch Retro Rewind update process for relative user folders

- WheelWizard.Test/Features/GameBananaTests.cs
- WheelWizard/Features/AutoUpdating/AutoUpdatingExtensions.cs
- WheelWizard/Features/AutoUpdating/Platforms/.gitattributes
- WheelWizard/Features/AutoUpdating/Platforms/LinuxUpdatePlatform.cs
- WheelWizard/Features/AutoUpdating/Platforms/WindowsUpdatePlatform.cs
- WheelWizard/Helpers/EnvHelper.cs
- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
- WheelWizard/Services/Launcher/Helpers/MiiChannelLaunchHelper.cs
- WheelWizard/Services/Launcher/RrLauncher.cs
- WheelWizard/Services/Storage/FilePickerHelper.cs
- WheelWizard/Views/Pages/Settings/WhWzSettings.axaml.cs
Mitigate potential unintentional command injections in commands using paths dependent on the environment or user input. We now use the right quoting/escaping methods depending on the context (e.g. the OS).
Ensure that the auto updater still works correctly on Windows. Also, test the Linux auto updater (comment out the line for that) with the WheelWizard executable in a directory with some special characters (spaces, quotes, ...)  – the script should be able to run without issues. In addition, it should be ensured that spaces or quotes in paths do not affect the program's ability to launch the game or open the folders (e.g. in `explorer.exe`). These changes have been tested on a fixed Flatpak build of Wheel Wizard: https://github.com/matellush/io.github.TeamWheelWizard.WheelWizard/commit/00 …
> fix: Properly quote paths in commands [needs additional cross-platform testing]

- WheelWizard/Services/Installation/RetroRewindUpdater.cs
Fix the check of the parent directory of files to delete to include the directory separator in order to prevent matching directories with a longer name but the same prefix (just like `ExtractZipFile` does it).
Same as #141
The destination directory that is supposed to be at the start of the files to delete additionally contains the path separator at the end now.
#141
> fix: Add missing directory separator to required parent directory

- WheelWizard/Views/Pages/UserProfilePage.axaml.cs
Fix the issue where the online status is never shown on a license profile, even after switching pages.
Get one of your license profiles into a room and check if the online status is updated and the "View Room" button works.
The `IsOnline` property is now actually assigned to the `UserProfilePage` from the `currentPlayer`.
#159
> fix: Correctly update online status of current user profile

- WheelWizard/Services/PathManager.cs
In some cases, the `-p` option for `flatpak run` commands would make sense to specify. The option makes sure that the entire Flatpak sandbox of the Dolphin Flatpak would get killed when the launching parent process dies. Without this option, there can be edge cases where a Dolphin process would remain even after everything else has been killed.
Specify any of the newly added command options and make sure the permissions are set correctly for the launched Dolphin process even with the new `-p` flag.
The list of known Dolphin Flatpak commands has been extended to account for the `-p` option.
> feat: Allow `-p` option for `flatpak-run(1)` commands

- WheelWizard/Services/PathManager.cs
- WheelWizard/Services/Settings/SettingsManager.cs
Make Wheel Wizard use the `Load` and `Wii` folders that Dolphin actually uses.
Override the default `Load` and `Wii` folder paths using `Dolphin.ini` with the `LoadPath` and `NANDRootPath` settings in `[General]`. The path to the Mii database should follow the new `Wii` path and the path to the game installation or the license should follow the new `Load` folder. Standard configurations without overrides should continue to work.
The `LoadFolderPath` and `WiiFolderPath` getters have been changed to prioritize the Dolphin setting if present. For this, two Dolphin settings have been added that are effectively only read from. As the `RR_REGION` default value seems to have been broken anyway, it is set to `None` because it is not possible to determine without first determining the …
> fix: Respect Dolphin settings for `Load` and `Wii` folders

- WheelWizard/Services/Launcher/Helpers/DolphinLaunchHelper.cs
It seems like some conflict might have been resolved in a wrong way – commit b932d4971c719b8982ab192c582aeb5d00a012e0 used the `EnvHelper` method to quote the `--filesystem` argument instead of using double quotes (cf. https://github.com/TeamWheelWizard/WheelWizard/pull/149/commits/b932d4971c719b8982ab192c582aeb5d00a012e0#diff-dc65a8a0511953e6f440b3ecb200a1402532025d9c492f0745c3f2ddb64b33bcL94), but the change seems to be gone. This PR's purpose is to fix it again.
> fix: Use correct quoting again

- WheelWizard/Services/Settings/SettingsManager.cs
This is a minor fix for correctness of the validation of Unix commands as the Dolphin location in Wheel Wizard. Since the setting is always interpreted as a shell command, it does not make sense to check for file existence. For example, in the case of a file path with a space and missing quotes around it, `FileHelper.FileExists(pathOrCommand)` would return `true` even if that path would fail when trying to launch Dolphin, since the shell would try to execute the command up until the first space, the rest being arguments.
Both relative paths (dot-relative) and absolute paths will continue to work and validation would still succeed with this change. Note that any executable paths with spaces need to be quoted (or escaped) (which the GUI will do automatically) on Linux or macOS, as one would …
> fix: Drop incorrect expression in Dolphin location validation

- WheelWizard.Test/WheelWizard.Test.csproj
Removed duplicate package ref to ``Testably.Abstractions.Testing`` from the ``WheelWizard.Test.csproj`` file
-not applicable-
removed a duplicate ``<PackageReference>`` tag
https://github.com/TeamWheelWizard/WheelWizard/issues/178
> fix: remove duplicate package ref from WheelWizard.Test.csproj

- WheelWizard/Features/CustomDistributions/IDistribution.cs
- WheelWizard/Features/CustomDistributions/RetroRewind.cs
- WheelWizard/Services/Launcher/RrLauncher.cs
- WheelWizard/Services/PathManager.cs
this PR fixes the crash when freshly installing RR.
1. delete the ``Riivolution`` or ``WheelWizard`` directory of the ``<UserFolderPath>/Load/Riivolution/WheelWizard/`` path.
2. try installing RetroRewind via the GUI
inserted a few lines in ``WheelWizard/Features/CustomDistributions/RetroRewind.cs`` before copying the extracted RR files to create the parent directory if necessary.
https://github.com/TeamWheelWizard/WheelWizard/issues/168
> fix: initial RetroRewind installation crashes WheelWizard

- WheelWizard/Features/CustomDistributions/RetroRewind.cs
change the RetroRewind installation from using ``Directory.Move`` to ``File.Move`` to address the issue mentioned below
make sure WheelWizard and the Dolphin User folder are on different drives, then try installing RetroRewind.
I removed the Directory.Move call and instead copy over each file individually.
I also moved the cleanup of previous installations into the RemoveAsync() function.
https://github.com/TeamWheelWizard/WheelWizard/issues/181
> fix: installing across volumes doesnt work

- WheelWizard/Services/ModManager.cs
- WheelWizard/Views/Pages/UserProfilePage.axaml.cs
- WheelWizard/Views/Popups/Generic/TextInputWindow.axaml.cs
- WheelWizard/Views/Popups/MiiManagement/MiiEditor/EditorGeneral.axaml.cs
Fix differences in name validation related to the use of `Trim()` on the validated strings.
Check the rename/naming popups for mod names, license names, and also those (including the "complex" popup) of the Mii editor for their behaviors with leading or trailing spaces with respect to the length of given names.
Drop `Trim()` from the `TextInputView` – now the validation methods should themselves trim the text for length checks etc.
No related issue
> fix: Always trim strings to validate separately if required

- WheelWizard/Models/RRInfo/RrRoom.cs
Update the possible descriptions of the region / game mode an online room is assigned.
Open the app and check if information about currently open rooms makes sense.
The mappings of online room regions for various packs have been updated to currently known values.
No open issue.
> fix: Update online room regional mappings

- Directory.Build.props
- WheelWizard.sln
- WheelWizard/Features/CustomDistributions/CustomDistributionSingletonService.cs
- WheelWizard/Features/CustomDistributions/RetroRewind.cs
- WheelWizard/Helpers/FileHelper.cs
- WheelWizard/Logging.cs
- WheelWizard/Resources/Languages/Phrases.Designer.cs
- WheelWizard/Resources/Languages/Phrases.resx
- WheelWizard/Resources/Languages/Settings.Designer.cs
- WheelWizard/Resources/Languages/Settings.resx
- WheelWizard/Services/PathManager.cs
- WheelWizard/Services/Storage/FilePickerHelper.cs
- WheelWizard/Views/Pages/Settings/AppInfo.axaml
- WheelWizard/Views/Pages/Settings/AppInfo.axaml.cs
- WheelWizard/Views/Pages/Settings/SettingsPage.axaml
- WheelWizard/Views/Pages/Settings/SettingsPage.axaml.cs
- WheelWizard/Views/Pages/Settings/WhWzSettings.axaml
- WheelWizard/Views/Pages/Settings/WhWzSettings.axaml.cs
Adding support for the changing of the wheel wizard app data folder
> custom Wheel Wizard data folder
